package:
  name: scippneutron
  version: {{ GIT_DESCRIBE_TAG }}

source:
  path: ..

requirements:
  build:
    - boost-cpp
    - cmake
    - gxx_linux-64 9.3.* [linux64]
    - git
    - ninja
    - python {{ python }}
    - scipp
    - tbb-devel
  run:
    - python {{ python }}
    - scipp
    - h5py

test:
  imports:
    - scippneutron
    - neutron
  requires:
    - h5py
    - ipywidgets
    - matplotlib-base
    - psutil
    - pytest
    - pytest-asyncio
    - pythreejs
    - Pillow
    - mantid-framework [not win]
    - pip:
        - confluent-kafka
        - ess-streaming-data-types
  source_files:
    - python/tests/
    - neutron/
  commands:
    - python -m pytest -v

build:
  number: {{ environ.get('GIT_DESCRIBE_NUMBER', 0) }}
  script_env:
    - CC
    - CXX
    - OSX_VERSION

about:
  home: https://github.com/scipp/scippneutron
  license: GPLv3
  summary: Neutron scattering tools for Data Reduction
  description: Neutron scattering tools for Data Reduction
  dev_url: https://github.com/scipp/scippneutron
  doc_url:
