package:
  name: scipp-neutron 
  version: {{ GIT_DESCRIBE_TAG }}

source:
  path: .. 

requirements:
  run:
    - python {{ python }}
    - scipp

test:
  imports:
    - scipp
    - neutron
    - neutron.imaging
  requires:
    - pytest
  source_files:
    - neutron/
  commands:
    - python -m pytest -v

about:
  home: https://github.com/scipp/scipp-neutron
  license: GPLv3
  summary: Neutron scattering tools for Data Reduction
  description: Neutron scattering tools for Data Reduction 
  dev_url: https://github.com/scipp/scipp-neutron
  doc_url: 
