trigger:
  - latest
  - packaging

pr: none

stages:

  - stage: 'test'
    displayName: 'Python tests'

    jobs:
      - job: 'python_test'
        displayName: 'Python tests'
        timeoutInMinutes: 20
        pool:
          vmImage: 'ubuntu-18.04'
        steps:
          - checkout: self
            submodules: true
          - bash: echo "##vso[task.prependpath]$CONDA/bin"
            displayName: 'add conda to PATH'
          - bash: |
             set -ex
             conda --version
             conda config --set always_yes yes --set changeps1 no
             conda env create -f scipp-neutron-latest.yaml
            displayName: 'create anaconda environment'
          - bash: |
             source activate scipp-neutron-latest
             conda env list
             conda build conda/ -c scipp/label/dev 
            displayName: 'package'
