trigger:
  branches:
    exclude:
      - '*'

pr:
  autoCancel: true
  branches:
    include:
      - '*'

variables:
  is_master: $[eq(variables['System.PullRequest.TargetBranch'], 'master')]
  target_branch: $[variables['System.PullRequest.TargetBranch']]

stages:

  - stage: 'test'
    displayName: 'Python tests'

    jobs:
      - job: 'python_test'
        displayName: 'Python tests'
        timeoutInMinutes: 20
        pool:
          vmImage: 'ubuntu-18.04'
        steps:
          - checkout: self
            submodules: true
          - bash: echo "##vso[task.prependpath]$CONDA/bin"
            displayName: 'add conda to PATH'
          - bash: |
             set -ex
             echo is master $(is_master)
             echo target branch $(System.PullRequest.TargetBranch)
             # If master use stable/release scipp version from channel, otherwise latest
             scippdependency=scipp-neutron
             if [ $(is_master) == False ]; then
                 scippdependency=scipp-neutron-latest
             fi
             echo using $scippdependency;
             echo "##vso[task.setvariable variable=scippdependency]$scippdependency"
             conda --version
             conda config --set always_yes yes --set changeps1 no
             conda env create -f ${scippdependency}.yaml
            displayName: 'create anaconda environment'
          - bash: |
             conda activating $(scippdependency)
             conda activate $(scippdependency)
             conda env list
             python -m pytest --junitxml=junit/unit-test.xml
            displayName: 'run pytest'
          - task: PublishTestResults@2
            inputs:
              testResultsFiles: 'junit/*.xml'
            condition: succeededOrFailed()
